# Generated by Django 4.2.7 on 2023-12-03 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
